// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/plumv/KratosProject/helloworld/internal/biz"
	"github.com/plumv/KratosProject/helloworld/internal/conf"
	"github.com/plumv/KratosProject/helloworld/internal/data"
	"github.com/plumv/KratosProject/helloworld/internal/server"
	"github.com/plumv/KratosProject/helloworld/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	// 根据confData+logger调用NewData构建dataData和cleanup
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	// 构建repo
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	// 构建 usecase
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	// 构建 service
	greeterService := service.NewGreeterService(greeterUsecase)
	// 构建grpc服务
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	// 构建http该服务
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	// 创建应用程序
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
