syntax = "proto3";

package base;

option go_package = "api/base;base";
import "openapi/v3/annotations.proto";

message SortReq{
  option (openapi.v3.schema) = {
    title: "排序请求";
  };
  string order = 1 [
    (openapi.v3.property) = {
      nullable: false;
      title: "排序字段";
    }
  ];
  bool sort = 2 [
    (openapi.v3.property) = {
      nullable: false;
      title: "是否顺序排序";
    }
  ];
}

message PageReq{
  option (openapi.v3.schema) = {
    title: "分页请求";
  };
  int32 page_size = 1 [
    (openapi.v3.property) = {
      nullable: false;
      title: "一页大小";
    }
  ];
  int32 page = 2 [
    (openapi.v3.property) = {
      nullable: false;
      title: "页码";
    }
  ];
}

message ResultResp{
  option (openapi.v3.schema) = {
    title: "结果状态响应";
  };
  int32 code = 1 [
    (openapi.v3.property) = {
      nullable: false;
      title: "响应状态";
    }
  ];
  string msg = 2 [
    (openapi.v3.property) = {
      nullable: false;
      title: "状态信息";
    }
  ];
}

message PageResp{
  option (openapi.v3.schema) = {
    title: "分页响应";
  };
  int64 total = 1 [
    (openapi.v3.property) = {
      nullable: false;
      title: "总数量";
    }
  ];
}
