// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BossUserColumns holds the columns for the "boss_user" table.
	BossUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键"},
		{Name: "delete_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint64, Nullable: true, Comment: "创建人"},
		{Name: "updated_by", Type: field.TypeUint64, Nullable: true, Comment: "更新人"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "username", Type: field.TypeString, Comment: "用户名"},
		{Name: "password", Type: field.TypeString, Comment: "密码"},
		{Name: "age", Type: field.TypeInt32, Comment: "年龄"},
	}
	// BossUserTable holds the schema information for the "boss_user" table.
	BossUserTable = &schema.Table{
		Name:       "boss_user",
		Columns:    BossUserColumns,
		PrimaryKey: []*schema.Column{BossUserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_delete_at",
				Unique:  false,
				Columns: []*schema.Column{BossUserColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BossUserTable,
	}
)

func init() {
	BossUserTable.Annotation = &entsql.Annotation{
		Table: "boss_user",
	}
}
