// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: boss/boss.proto

package boss

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_boss_boss_proto protoreflect.FileDescriptor

const file_boss_boss_proto_rawDesc = "" +
	"\n" +
	"\x0fboss/boss.proto\x12\x04boss\x1a\x1cgoogle/api/annotations.proto\x1a\x1copenapi/v3/annotations.proto\x1a\x0fboss/user.proto\x1a\x0fboss/role.proto2\x9a\a\n" +
	"\x04User\x12\x97\x01\n" +
	"\n" +
	"CreateUser\x12\x17.boss.CreateUserRequest\x1a\x15.boss.CreateUserReply\"Y\xbaGB\n" +
	"\f用户服务\x12\f创建用户\x1a$传入用户基本信息创建用户\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/user\x12\x97\x01\n" +
	"\n" +
	"UpdateUser\x12\x17.boss.UpdateUserRequest\x1a\x15.boss.UpdateUserReply\"Y\xbaG>\n" +
	"\f用户服务\x12\f更新用户\x1a 根据用户ID更新用户信息\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/api/user/:id\x12\x8e\x01\n" +
	"\n" +
	"DeleteUser\x12\x17.boss.DeleteUserRequest\x1a\x15.boss.DeleteUserReply\"P\xbaG8\n" +
	"\f用户服务\x12\f删除用户\x1a\x1a根据用户ID删除用户\x82\xd3\xe4\x93\x02\x0f*\r/api/user/:id\x12\x8b\x01\n" +
	"\aGetUser\x12\x14.boss.GetUserRequest\x1a\x12.boss.GetUserReply\"V\xbaG>\n" +
	"\f用户服务\x12\f查找用户\x1a 根据用户ID查询唯一用户\x82\xd3\xe4\x93\x02\x0f\x12\r/api/user/:id\x12\x96\x01\n" +
	"\bListUser\x12\x15.boss.ListUserRequest\x1a\x13.boss.ListUserReply\"^\xbaGB\n" +
	"\f用户服务\x12\x12查询用户列表\x1a\x1e条件查询所有用户信息\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/user/list\x12\xa5\x01\n" +
	"\bPageUser\x12\x15.boss.PageUserRequest\x1a\x13.boss.PageUserReply\"m\xbaGQ\n" +
	"\f用户服务\x12\x12分页查询用户\x1a-条件查询所有用户信息并分页展示\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/user/pageB\xe2\x01\xbaG\xc7\x01\x12\xb4\x01\n" +
	"\rboss examples\">\n" +
	"\x11gRPC-http project\x12\x17https://127.0.0.1:8000/\x1a\x10none@example.com*^\n" +
	"\x14BSD 3-Clause License\x12Fhttps://github.com/grpc-ecosystem/grpc-gateway/blob/master/LICENSE.txt2\x031.0:\x0e\n" +
	"\f用户服务\n" +
	"\x04bossP\x01Z\rapi/boss;bossb\x06proto3"

var file_boss_boss_proto_goTypes = []any{
	(*CreateUserRequest)(nil), // 0: boss.CreateUserRequest
	(*UpdateUserRequest)(nil), // 1: boss.UpdateUserRequest
	(*DeleteUserRequest)(nil), // 2: boss.DeleteUserRequest
	(*GetUserRequest)(nil),    // 3: boss.GetUserRequest
	(*ListUserRequest)(nil),   // 4: boss.ListUserRequest
	(*PageUserRequest)(nil),   // 5: boss.PageUserRequest
	(*CreateUserReply)(nil),   // 6: boss.CreateUserReply
	(*UpdateUserReply)(nil),   // 7: boss.UpdateUserReply
	(*DeleteUserReply)(nil),   // 8: boss.DeleteUserReply
	(*GetUserReply)(nil),      // 9: boss.GetUserReply
	(*ListUserReply)(nil),     // 10: boss.ListUserReply
	(*PageUserReply)(nil),     // 11: boss.PageUserReply
}
var file_boss_boss_proto_depIdxs = []int32{
	0,  // 0: boss.User.CreateUser:input_type -> boss.CreateUserRequest
	1,  // 1: boss.User.UpdateUser:input_type -> boss.UpdateUserRequest
	2,  // 2: boss.User.DeleteUser:input_type -> boss.DeleteUserRequest
	3,  // 3: boss.User.GetUser:input_type -> boss.GetUserRequest
	4,  // 4: boss.User.ListUser:input_type -> boss.ListUserRequest
	5,  // 5: boss.User.PageUser:input_type -> boss.PageUserRequest
	6,  // 6: boss.User.CreateUser:output_type -> boss.CreateUserReply
	7,  // 7: boss.User.UpdateUser:output_type -> boss.UpdateUserReply
	8,  // 8: boss.User.DeleteUser:output_type -> boss.DeleteUserReply
	9,  // 9: boss.User.GetUser:output_type -> boss.GetUserReply
	10, // 10: boss.User.ListUser:output_type -> boss.ListUserReply
	11, // 11: boss.User.PageUser:output_type -> boss.PageUserReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_boss_boss_proto_init() }
func file_boss_boss_proto_init() {
	if File_boss_boss_proto != nil {
		return
	}
	file_boss_user_proto_init()
	file_boss_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_boss_proto_rawDesc), len(file_boss_boss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boss_boss_proto_goTypes,
		DependencyIndexes: file_boss_boss_proto_depIdxs,
	}.Build()
	File_boss_boss_proto = out.File
	file_boss_boss_proto_goTypes = nil
	file_boss_boss_proto_depIdxs = nil
}
