// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: boss/role.proto

package boss

import (
	base "api/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleReply) Reset() {
	*x = RoleReply{}
	mi := &file_boss_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleReply) ProtoMessage() {}

func (x *RoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleReply.ProtoReflect.Descriptor instead.
func (*RoleReply) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{0}
}

func (x *RoleReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleReply) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_boss_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_boss_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type CreateRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Data          *RoleReply             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReply) Reset() {
	*x = CreateRoleReply{}
	mi := &file_boss_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReply) ProtoMessage() {}

func (x *CreateRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReply.ProtoReflect.Descriptor instead.
func (*CreateRoleReply) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *CreateRoleReply) GetData() *RoleReply {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Data          *RoleReply             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReply) Reset() {
	*x = UpdateRoleReply{}
	mi := &file_boss_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReply) ProtoMessage() {}

func (x *UpdateRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReply.ProtoReflect.Descriptor instead.
func (*UpdateRoleReply) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoleReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *UpdateRoleReply) GetData() *RoleReply {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_boss_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleReply) Reset() {
	*x = DeleteRoleReply{}
	mi := &file_boss_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleReply) ProtoMessage() {}

func (x *DeleteRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleReply.ProtoReflect.Descriptor instead.
func (*DeleteRoleReply) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRoleReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_boss_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Data          *RoleReply             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleReply) Reset() {
	*x = GetRoleReply{}
	mi := &file_boss_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleReply) ProtoMessage() {}

func (x *GetRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleReply.ProtoReflect.Descriptor instead.
func (*GetRoleReply) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoleReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *GetRoleReply) GetData() *RoleReply {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRoleRequest) Reset() {
	*x = QueryRoleRequest{}
	mi := &file_boss_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoleRequest) ProtoMessage() {}

func (x *QueryRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoleRequest.ProtoReflect.Descriptor instead.
func (*QueryRoleRequest) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{9}
}

func (x *QueryRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryRoleRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type ListRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sort          *base.SortReq          `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Query         *QueryRoleRequest      `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleRequest) Reset() {
	*x = ListRoleRequest{}
	mi := &file_boss_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleRequest) ProtoMessage() {}

func (x *ListRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleRequest.ProtoReflect.Descriptor instead.
func (*ListRoleRequest) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoleRequest) GetSort() *base.SortReq {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListRoleRequest) GetQuery() *QueryRoleRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Data          []*RoleReply           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleReply) Reset() {
	*x = ListRoleReply{}
	mi := &file_boss_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleReply) ProtoMessage() {}

func (x *ListRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleReply.ProtoReflect.Descriptor instead.
func (*ListRoleReply) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{11}
}

func (x *ListRoleReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *ListRoleReply) GetData() []*RoleReply {
	if x != nil {
		return x.Data
	}
	return nil
}

type PageRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *base.PageReq          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Sort          *base.SortReq          `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Query         *QueryRoleRequest      `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRoleRequest) Reset() {
	*x = PageRoleRequest{}
	mi := &file_boss_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRoleRequest) ProtoMessage() {}

func (x *PageRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRoleRequest.ProtoReflect.Descriptor instead.
func (*PageRoleRequest) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{12}
}

func (x *PageRoleRequest) GetPage() *base.PageReq {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PageRoleRequest) GetSort() *base.SortReq {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *PageRoleRequest) GetQuery() *QueryRoleRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type PageRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Page          *base.PageResp         `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Data          []*RoleReply           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRoleReply) Reset() {
	*x = PageRoleReply{}
	mi := &file_boss_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRoleReply) ProtoMessage() {}

func (x *PageRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRoleReply.ProtoReflect.Descriptor instead.
func (*PageRoleReply) Descriptor() ([]byte, []int) {
	return file_boss_role_proto_rawDescGZIP(), []int{13}
}

func (x *PageRoleReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *PageRoleReply) GetPage() *base.PageResp {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PageRoleReply) GetData() []*RoleReply {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_boss_role_proto protoreflect.FileDescriptor

const file_boss_role_proto_rawDesc = "" +
	"\n" +
	"\x0fboss/role.proto\x12\x04boss\x1a\x0fbase/base.proto\"C\n" +
	"\tRoleReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\";\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"K\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\"V\n" +
	"\x0fCreateRoleReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.boss.RoleReplyR\x04data\"V\n" +
	"\x0fUpdateRoleReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.boss.RoleReplyR\x04data\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x0fDeleteRoleReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r\" \n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"S\n" +
	"\fGetRoleReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.boss.RoleReplyR\x04data\"8\n" +
	"\x10QueryRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\"b\n" +
	"\x0fListRoleRequest\x12!\n" +
	"\x04sort\x18\x01 \x01(\v2\r.base.SortReqR\x04sort\x12,\n" +
	"\x05query\x18\x02 \x01(\v2\x16.boss.QueryRoleRequestR\x05query\"T\n" +
	"\rListRoleReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r\x12#\n" +
	"\x04data\x18\x02 \x03(\v2\x0f.boss.RoleReplyR\x04data\"\x85\x01\n" +
	"\x0fPageRoleRequest\x12!\n" +
	"\x04page\x18\x01 \x01(\v2\r.base.PageReqR\x04page\x12!\n" +
	"\x04sort\x18\x02 \x01(\v2\r.base.SortReqR\x04sort\x12,\n" +
	"\x05query\x18\x03 \x01(\v2\x16.boss.QueryRoleRequestR\x05query\"x\n" +
	"\rPageRoleReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r\x12\"\n" +
	"\x04page\x18\x02 \x01(\v2\x0e.base.PageRespR\x04page\x12#\n" +
	"\x04data\x18\x03 \x03(\v2\x0f.boss.RoleReplyR\x04dataB\x0fZ\rapi/boss;bossb\x06proto3"

var (
	file_boss_role_proto_rawDescOnce sync.Once
	file_boss_role_proto_rawDescData []byte
)

func file_boss_role_proto_rawDescGZIP() []byte {
	file_boss_role_proto_rawDescOnce.Do(func() {
		file_boss_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_role_proto_rawDesc), len(file_boss_role_proto_rawDesc)))
	})
	return file_boss_role_proto_rawDescData
}

var file_boss_role_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_boss_role_proto_goTypes = []any{
	(*RoleReply)(nil),         // 0: boss.RoleReply
	(*CreateRoleRequest)(nil), // 1: boss.CreateRoleRequest
	(*UpdateRoleRequest)(nil), // 2: boss.UpdateRoleRequest
	(*CreateRoleReply)(nil),   // 3: boss.CreateRoleReply
	(*UpdateRoleReply)(nil),   // 4: boss.UpdateRoleReply
	(*DeleteRoleRequest)(nil), // 5: boss.DeleteRoleRequest
	(*DeleteRoleReply)(nil),   // 6: boss.DeleteRoleReply
	(*GetRoleRequest)(nil),    // 7: boss.GetRoleRequest
	(*GetRoleReply)(nil),      // 8: boss.GetRoleReply
	(*QueryRoleRequest)(nil),  // 9: boss.QueryRoleRequest
	(*ListRoleRequest)(nil),   // 10: boss.ListRoleRequest
	(*ListRoleReply)(nil),     // 11: boss.ListRoleReply
	(*PageRoleRequest)(nil),   // 12: boss.PageRoleRequest
	(*PageRoleReply)(nil),     // 13: boss.PageRoleReply
	(*base.ResultResp)(nil),   // 14: base.ResultResp
	(*base.SortReq)(nil),      // 15: base.SortReq
	(*base.PageReq)(nil),      // 16: base.PageReq
	(*base.PageResp)(nil),     // 17: base.PageResp
}
var file_boss_role_proto_depIdxs = []int32{
	14, // 0: boss.CreateRoleReply.r:type_name -> base.ResultResp
	0,  // 1: boss.CreateRoleReply.data:type_name -> boss.RoleReply
	14, // 2: boss.UpdateRoleReply.r:type_name -> base.ResultResp
	0,  // 3: boss.UpdateRoleReply.data:type_name -> boss.RoleReply
	14, // 4: boss.DeleteRoleReply.r:type_name -> base.ResultResp
	14, // 5: boss.GetRoleReply.r:type_name -> base.ResultResp
	0,  // 6: boss.GetRoleReply.data:type_name -> boss.RoleReply
	15, // 7: boss.ListRoleRequest.sort:type_name -> base.SortReq
	9,  // 8: boss.ListRoleRequest.query:type_name -> boss.QueryRoleRequest
	14, // 9: boss.ListRoleReply.r:type_name -> base.ResultResp
	0,  // 10: boss.ListRoleReply.data:type_name -> boss.RoleReply
	16, // 11: boss.PageRoleRequest.page:type_name -> base.PageReq
	15, // 12: boss.PageRoleRequest.sort:type_name -> base.SortReq
	9,  // 13: boss.PageRoleRequest.query:type_name -> boss.QueryRoleRequest
	14, // 14: boss.PageRoleReply.r:type_name -> base.ResultResp
	17, // 15: boss.PageRoleReply.page:type_name -> base.PageResp
	0,  // 16: boss.PageRoleReply.data:type_name -> boss.RoleReply
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_boss_role_proto_init() }
func file_boss_role_proto_init() {
	if File_boss_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_role_proto_rawDesc), len(file_boss_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_role_proto_goTypes,
		DependencyIndexes: file_boss_role_proto_depIdxs,
		MessageInfos:      file_boss_role_proto_msgTypes,
	}.Build()
	File_boss_role_proto = out.File
	file_boss_role_proto_goTypes = nil
	file_boss_role_proto_depIdxs = nil
}
