// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: boss/user.proto

package boss

import (
	base "api/base"
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           *wrapperspb.Int32Value  `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	Email         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReply) Reset() {
	*x = UserReply{}
	mi := &file_boss_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReply) ProtoMessage() {}

func (x *UserReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReply.ProtoReflect.Descriptor instead.
func (*UserReply) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserReply) GetId() *wrapperspb.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UserReply) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UserReply) GetAge() *wrapperspb.Int32Value {
	if x != nil {
		return x.Age
	}
	return nil
}

func (x *UserReply) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	Email         *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_boss_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CreateUserRequest) GetAge() *wrapperspb.Int32Value {
	if x != nil {
		return x.Age
	}
	return nil
}

func (x *CreateUserRequest) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *CreateUserRequest) GetPassword() *wrapperspb.StringValue {
	if x != nil {
		return x.Password
	}
	return nil
}

type CreateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Data          *UserReply             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReply) Reset() {
	*x = CreateUserReply{}
	mi := &file_boss_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReply) ProtoMessage() {}

func (x *CreateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReply.ProtoReflect.Descriptor instead.
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *CreateUserReply) GetData() *UserReply {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           *wrapperspb.Int32Value  `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	Email         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_boss_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() *wrapperspb.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateUserRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateUserRequest) GetAge() *wrapperspb.Int32Value {
	if x != nil {
		return x.Age
	}
	return nil
}

func (x *UpdateUserRequest) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

type UpdateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Data          *UserReply             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReply) Reset() {
	*x = UpdateUserReply{}
	mi := &file_boss_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReply) ProtoMessage() {}

func (x *UpdateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReply.ProtoReflect.Descriptor instead.
func (*UpdateUserReply) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *UpdateUserReply) GetData() *UserReply {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_boss_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserRequest) GetId() *wrapperspb.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReply) Reset() {
	*x = DeleteUserReply{}
	mi := &file_boss_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReply) ProtoMessage() {}

func (x *DeleteUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReply.ProtoReflect.Descriptor instead.
func (*DeleteUserReply) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_boss_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRequest) GetId() *wrapperspb.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Data          *UserReply             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReply) Reset() {
	*x = GetUserReply{}
	mi := &file_boss_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReply) ProtoMessage() {}

func (x *GetUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReply.ProtoReflect.Descriptor instead.
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *GetUserReply) GetData() *UserReply {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryUserRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserRequest) Reset() {
	*x = QueryUserRequest{}
	mi := &file_boss_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserRequest) ProtoMessage() {}

func (x *QueryUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserRequest.ProtoReflect.Descriptor instead.
func (*QueryUserRequest) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{9}
}

func (x *QueryUserRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *QueryUserRequest) GetAge() *wrapperspb.Int32Value {
	if x != nil {
		return x.Age
	}
	return nil
}

type ListUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sort          *base.SortReq          `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Query         *QueryUserRequest      `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRequest) Reset() {
	*x = ListUserRequest{}
	mi := &file_boss_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRequest) ProtoMessage() {}

func (x *ListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRequest.ProtoReflect.Descriptor instead.
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserRequest) GetSort() *base.SortReq {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListUserRequest) GetQuery() *QueryUserRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Data          []*UserReply           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReply) Reset() {
	*x = ListUserReply{}
	mi := &file_boss_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReply) ProtoMessage() {}

func (x *ListUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReply.ProtoReflect.Descriptor instead.
func (*ListUserReply) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{11}
}

func (x *ListUserReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *ListUserReply) GetData() []*UserReply {
	if x != nil {
		return x.Data
	}
	return nil
}

type PageUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *base.PageReq          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Sort          *base.SortReq          `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Query         *QueryUserRequest      `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageUserRequest) Reset() {
	*x = PageUserRequest{}
	mi := &file_boss_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageUserRequest) ProtoMessage() {}

func (x *PageUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageUserRequest.ProtoReflect.Descriptor instead.
func (*PageUserRequest) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{12}
}

func (x *PageUserRequest) GetPage() *base.PageReq {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PageUserRequest) GetSort() *base.SortReq {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *PageUserRequest) GetQuery() *QueryUserRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type PageUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *base.ResultResp       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Page          *base.PageResp         `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Data          []*UserReply           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageUserReply) Reset() {
	*x = PageUserReply{}
	mi := &file_boss_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageUserReply) ProtoMessage() {}

func (x *PageUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_boss_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageUserReply.ProtoReflect.Descriptor instead.
func (*PageUserReply) Descriptor() ([]byte, []int) {
	return file_boss_user_proto_rawDescGZIP(), []int{13}
}

func (x *PageUserReply) GetR() *base.ResultResp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *PageUserReply) GetPage() *base.PageResp {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PageUserReply) GetData() []*UserReply {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_boss_user_proto protoreflect.FileDescriptor

const file_boss_user_proto_rawDesc = "" +
	"\n" +
	"\x0fboss/user.proto\x12\x04boss\x1a\x0fbase/base.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1copenapi/v3/annotations.proto\x1a\x1bbuf/validate/validate.proto\"\xb0\x02\n" +
	"\tUserReply\x129\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\v\xbaG\bJ\x06主键R\x02id\x12@\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueB\x0e\xbaG\vJ\t用户名R\x04name\x12@\n" +
	"\x03age\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueB\x11\xbaG\x0eJ\f用户年龄R\x03age\x12E\n" +
	"\x05email\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB\x11\xbaG\x0eJ\f用户邮箱R\x05email:\x1d\xbaG\x1aJ\x18用户基本信息响应\"\xe9\x02\n" +
	"\x11CreateUserRequest\x12F\n" +
	"\x04name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\x14\xbaG\vJ\t用户名\xbaH\x03\xc8\x01\x01R\x04name\x12M\n" +
	"\x03age\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueB\x1e\xbaG\x0eJ\f用户年龄\xbaH\n" +
	"\xc8\x01\x01\x1a\x05\x18\xc8\x01(\x00R\x03age\x12O\n" +
	"\x05email\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB\x1b\xbaG\x0eJ\f用户邮箱\xbaH\a\xc8\x01\x01r\x02`\x01R\x05email\x12Q\n" +
	"\bpassword\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB\x17\xbaG\x0eJ\f用户密码\xbaH\x03\xc8\x01\x01R\bpassword:\x19\xbaG\x16 \x01J\x12用户创建请求\"u\n" +
	"\x0fCreateUserReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.boss.UserReplyR\x04data:\x1d\xbaG\x1aJ\x18创建用户响应信息\"\xb2\x02\n" +
	"\x11UpdateUserRequest\x129\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\v\xbaG\bJ\x06主键R\x02id\x12@\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueB\x0e\xbaG\vJ\t用户名R\x04name\x12@\n" +
	"\x03age\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueB\x11\xbaG\x0eJ\f用户年龄R\x03age\x12E\n" +
	"\x05email\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB\x11\xbaG\x0eJ\f用户邮箱R\x05email:\x17\xbaG\x14J\x12更新用户请求\"o\n" +
	"\x0fUpdateUserReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.boss.UserReplyR\x04data:\x17\xbaG\x14J\x12用户更新响应\"g\n" +
	"\x11DeleteUserRequest\x129\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\v\xbaG\bJ\x06主键R\x02id:\x17\xbaG\x14J\x12用户删除请求\"J\n" +
	"\x0fDeleteUserReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r:\x17\xbaG\x14J\x12用户删除响应\"d\n" +
	"\x0eGetUserRequest\x129\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\v\xbaG\bJ\x06主键R\x02id:\x17\xbaG\x14J\x12获取用户请求\"l\n" +
	"\fGetUserReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.boss.UserReplyR\x04data:\x17\xbaG\x14J\x12获取用户响应\"\xc2\x01\n" +
	"\x10QueryUserRequest\x12M\n" +
	"\x04name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\x1b\xbaG\x18J\x16用户名-模糊查询R\x04name\x12@\n" +
	"\x03age\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueB\x11\xbaG\x0eJ\f用户年龄R\x03age:\x1d\xbaG\x1aJ\x18用户查询条件请求\"\x87\x01\n" +
	"\x0fListUserRequest\x12!\n" +
	"\x04sort\x18\x01 \x01(\v2\r.base.SortReqR\x04sort\x12,\n" +
	"\x05query\x18\x02 \x01(\v2\x16.boss.QueryUserRequestR\x05query:#\xbaG J\x1e条件查询所有用户请求\"\x8c\x01\n" +
	"\rListUserReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r\x126\n" +
	"\x04data\x18\x02 \x03(\v2\x0f.boss.UserReplyB\x11\xbaG\x0eJ\f用户列表R\x04data:#\xbaG J\x1e条件查询所有用户响应\"\xaa\x01\n" +
	"\x0fPageUserRequest\x12!\n" +
	"\x04page\x18\x01 \x01(\v2\r.base.PageReqR\x04page\x12!\n" +
	"\x04sort\x18\x02 \x01(\v2\r.base.SortReqR\x04sort\x12,\n" +
	"\x05query\x18\x03 \x01(\v2\x16.boss.QueryUserRequestR\x05query:#\xbaG J\x1e条件分页查询用户响应\"\xb0\x01\n" +
	"\rPageUserReply\x12\x1e\n" +
	"\x01r\x18\x01 \x01(\v2\x10.base.ResultRespR\x01r\x12\"\n" +
	"\x04page\x18\x02 \x01(\v2\x0e.base.PageRespR\x04page\x126\n" +
	"\x04data\x18\x03 \x03(\v2\x0f.boss.UserReplyB\x11\xbaG\x0eJ\f用户列表R\x04data:#\xbaG J\x1e条件分页查询用户响应B\x0fZ\rapi/boss;bossb\x06proto3"

var (
	file_boss_user_proto_rawDescOnce sync.Once
	file_boss_user_proto_rawDescData []byte
)

func file_boss_user_proto_rawDescGZIP() []byte {
	file_boss_user_proto_rawDescOnce.Do(func() {
		file_boss_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_user_proto_rawDesc), len(file_boss_user_proto_rawDesc)))
	})
	return file_boss_user_proto_rawDescData
}

var file_boss_user_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_boss_user_proto_goTypes = []any{
	(*UserReply)(nil),              // 0: boss.UserReply
	(*CreateUserRequest)(nil),      // 1: boss.CreateUserRequest
	(*CreateUserReply)(nil),        // 2: boss.CreateUserReply
	(*UpdateUserRequest)(nil),      // 3: boss.UpdateUserRequest
	(*UpdateUserReply)(nil),        // 4: boss.UpdateUserReply
	(*DeleteUserRequest)(nil),      // 5: boss.DeleteUserRequest
	(*DeleteUserReply)(nil),        // 6: boss.DeleteUserReply
	(*GetUserRequest)(nil),         // 7: boss.GetUserRequest
	(*GetUserReply)(nil),           // 8: boss.GetUserReply
	(*QueryUserRequest)(nil),       // 9: boss.QueryUserRequest
	(*ListUserRequest)(nil),        // 10: boss.ListUserRequest
	(*ListUserReply)(nil),          // 11: boss.ListUserReply
	(*PageUserRequest)(nil),        // 12: boss.PageUserRequest
	(*PageUserReply)(nil),          // 13: boss.PageUserReply
	(*wrapperspb.StringValue)(nil), // 14: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),  // 15: google.protobuf.Int32Value
	(*base.ResultResp)(nil),        // 16: base.ResultResp
	(*base.SortReq)(nil),           // 17: base.SortReq
	(*base.PageReq)(nil),           // 18: base.PageReq
	(*base.PageResp)(nil),          // 19: base.PageResp
}
var file_boss_user_proto_depIdxs = []int32{
	14, // 0: boss.UserReply.id:type_name -> google.protobuf.StringValue
	14, // 1: boss.UserReply.name:type_name -> google.protobuf.StringValue
	15, // 2: boss.UserReply.age:type_name -> google.protobuf.Int32Value
	14, // 3: boss.UserReply.email:type_name -> google.protobuf.StringValue
	14, // 4: boss.CreateUserRequest.name:type_name -> google.protobuf.StringValue
	15, // 5: boss.CreateUserRequest.age:type_name -> google.protobuf.Int32Value
	14, // 6: boss.CreateUserRequest.email:type_name -> google.protobuf.StringValue
	14, // 7: boss.CreateUserRequest.password:type_name -> google.protobuf.StringValue
	16, // 8: boss.CreateUserReply.r:type_name -> base.ResultResp
	0,  // 9: boss.CreateUserReply.data:type_name -> boss.UserReply
	14, // 10: boss.UpdateUserRequest.id:type_name -> google.protobuf.StringValue
	14, // 11: boss.UpdateUserRequest.name:type_name -> google.protobuf.StringValue
	15, // 12: boss.UpdateUserRequest.age:type_name -> google.protobuf.Int32Value
	14, // 13: boss.UpdateUserRequest.email:type_name -> google.protobuf.StringValue
	16, // 14: boss.UpdateUserReply.r:type_name -> base.ResultResp
	0,  // 15: boss.UpdateUserReply.data:type_name -> boss.UserReply
	14, // 16: boss.DeleteUserRequest.id:type_name -> google.protobuf.StringValue
	16, // 17: boss.DeleteUserReply.r:type_name -> base.ResultResp
	14, // 18: boss.GetUserRequest.id:type_name -> google.protobuf.StringValue
	16, // 19: boss.GetUserReply.r:type_name -> base.ResultResp
	0,  // 20: boss.GetUserReply.data:type_name -> boss.UserReply
	14, // 21: boss.QueryUserRequest.name:type_name -> google.protobuf.StringValue
	15, // 22: boss.QueryUserRequest.age:type_name -> google.protobuf.Int32Value
	17, // 23: boss.ListUserRequest.sort:type_name -> base.SortReq
	9,  // 24: boss.ListUserRequest.query:type_name -> boss.QueryUserRequest
	16, // 25: boss.ListUserReply.r:type_name -> base.ResultResp
	0,  // 26: boss.ListUserReply.data:type_name -> boss.UserReply
	18, // 27: boss.PageUserRequest.page:type_name -> base.PageReq
	17, // 28: boss.PageUserRequest.sort:type_name -> base.SortReq
	9,  // 29: boss.PageUserRequest.query:type_name -> boss.QueryUserRequest
	16, // 30: boss.PageUserReply.r:type_name -> base.ResultResp
	19, // 31: boss.PageUserReply.page:type_name -> base.PageResp
	0,  // 32: boss.PageUserReply.data:type_name -> boss.UserReply
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_boss_user_proto_init() }
func file_boss_user_proto_init() {
	if File_boss_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_user_proto_rawDesc), len(file_boss_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boss_user_proto_goTypes,
		DependencyIndexes: file_boss_user_proto_depIdxs,
		MessageInfos:      file_boss_user_proto_msgTypes,
	}.Build()
	File_boss_user_proto = out.File
	file_boss_user_proto_goTypes = nil
	file_boss_user_proto_depIdxs = nil
}
