syntax = "proto3";

package boss;
import "base/base.proto";

option go_package = "api/boss;boss";

message UserReply{
  int64  id = 1;
  string name = 2;
  int32 age = 3;
  string email = 4;
}

message CreateUserRequest {
  string name = 1;
  int32 age = 2;
  string email = 3;
  string password = 4;
}
message CreateUserReply {
  base.ResultResp r = 1;
  UserReply data = 2;
}

message UpdateUserRequest {
  int64  id = 1;
  string name = 2;
  int32 age = 3;
  string email = 4;
}
message UpdateUserReply {
  base.ResultResp r = 1;
  UserReply data = 2;
}

message DeleteUserRequest {
  int64  id = 1;
}
message DeleteUserReply {
  base.ResultResp r = 1;
}

message GetUserRequest {
  int64  id = 1;

}
message GetUserReply {
  base.ResultResp r = 1;
  UserReply data = 2;
}

message QueryUserRequest{
  string name = 1;
  int32 age = 2;
}

message ListUserRequest {
  base.SortReq sort = 1;
  QueryUserRequest query = 2;
}
message ListUserReply {
  base.ResultResp r = 1;
  repeated UserReply data = 2;
}

message PageUserRequest {
  base.PageReq page = 1;
  base.SortReq sort = 2;
  QueryUserRequest query = 3;
}

message PageUserReply{
  base.ResultResp r = 1;
  base.PageResp page = 2;
  repeated UserReply data = 3;
}